openapi: 3.2.0
info:
  version: 5.8.3
  title: Metrics Cache Countries API
  description: The API is designed to provide actual quality information for datasets.
  x-logo:
    url: images/logo
servers:
- url: ''
tags:
- name: Countries
paths:
  /countries:
    get:
      summary: List of all country metrics
      description: To get metadata quality score aggregated over parameter "country's id" and grouped by IDs of the countries of origin of the data make GET request to the specified URL of the API endpoint with the resource path "/countries" added at the end of the URL. The following five dimensions can be returned "findability", "accessibility", "interoperability", "reusability", and "contextuality". The aggregation process takes into account all datasets associated with catalogs sharing the same 'country ID,' which follows ISO 3166-1 ALPHA-3 Code standards for country ID abbreviations.
      operationId: getCountryMetrics
      tags:
      - Countries
      parameters:
      - $ref: '#/components/parameters/filter'
      responses:
        200:
          description: List of country metrics Objects.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      count:
                        type: integer
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/CountryMetrics'
        500:
          description: Could not fetch list of countries metrics.
  /countries/history:
    get:
      summary: Get historic aggregated metrics aggregated for all countries
      description: To retrieve the history of measurements for all available metadata that is accessible on the portal, aggregated over "country's id" and grouped by IDs of the countries of origin of the data, make a GET request to the specified URL of the API endpoint with the resource path "/countries/history" added at the end of the URL. Include the "startDate" query parameter in the request, providing a valid date value in the correct format. This specifies the start date for retrieving the measurement history. If successful, the response will contain metrics that cover the dimensions of "findability", "accessibility", "interoperability", "reusability", and "contextuality'. The aggregation process takes into account all datasets associated with catalogs sharing the same 'country ID,' which follows ISO 3166-1 ALPHA-3 Code standards for country ID abbreviations
      operationId: getHistoricCountryMetrics
      parameters:
      - $ref: '#/components/parameters/filter'
      - $ref: '#/components/parameters/startDate'
      - $ref: '#/components/parameters/endDate'
      - $ref: '#/components/parameters/resolution'
      tags:
      - Countries
      responses:
        200:
          description: List of historic country metrics Objects.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      count:
                        type: integer
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/HistoricCountryMetrics'
        400:
          description: Bad Request (e.g. startDate is later then endDate  ).
  /countries/{id}:
    get:
      tags:
      - Countries
      summary: Get metrics for a country
      description: To retrieve the measurements for metadata, aggregated over a designated country, make a GET request to the specified URL of the API endpoint with the resource path '/countries/{id}' added at the end of the URL and set the unique ID of the country as the {id} element of the URL. The country ID abbreviations should follow the ISO 3166-1 ALPHA-3 Code standards. If successful, the response will contain metrics that cover the dimensions of 'findability', 'accessibility', 'interoperability', 'reusability', and 'contextuality'. The aggregation process takes into account all datasets associated with catalog with specified 'country ID'.
      operationId: getSingleCountryMetrics
      parameters:
      - $ref: '#/components/parameters/countryId'
      - $ref: '#/components/parameters/filter'
      responses:
        200:
          description: Country metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      count:
                        type: integer
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/CountryMetrics'
        404:
          description: Country not found
  /countries/{id}/history:
    get:
      summary: Get historic metrics aggregated over a country
      description: To retrieve the history of measurements for metadata, aggregated over a designated country, make a GET request to the specified URL of the API endpoint with the resource path"/countries/{id}/history" added at the end of the URL and set the unique ID of the country as {id} element of the URL. The country ID abbreviations should follow the ISO 3166-1 ALPHA-3 Code standards. Include the "startDate" query parameter in the request, providing a valid date value in the correct format. This specifies the start date for retrieving the measurement history. If successful, the response will contain metrics that cover the dimensions of "findability", "accessibility", "interoperability", "reusability", and "contextuality'. The aggregation process takes into account all datasets associated with catalog with specified 'country ID'.
      operationId: getHistoricSingleCountryMetrics
      parameters:
      - $ref: '#/components/parameters/countryId'
      - $ref: '#/components/parameters/filter'
      - $ref: '#/components/parameters/startDate'
      - $ref: '#/components/parameters/endDate'
      - $ref: '#/components/parameters/resolution'
      tags:
      - Countries
      responses:
        200:
          description: Metrics regarding all available catalogues
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      count:
                        type: integer
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/HistoricCountryMetrics'
        400:
          description: Bad Request (e.g. startDate is later then endDate).
        404:
          description: Country not found
components:
  parameters:
    endDate:
      name: endDate
      in: query
      description: End date for which to retrieve the history. If no end date is specified, the currend date is used.
      schema:
        type: string
        format: date
      example: 2012-11-1
    filter:
      name: filter
      in: query
      description: Filter for one more multiple specific dimensions and/or the `score` and `info` object that should be returned.If present,  the document will contain _only_ the specified Dimensions. If this parameter is missing, the complete document will be returned.
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          enum:
          - findability
          - accessibility
          - interoperability
          - reusability
          - contextuality
          - score
          - info
    startDate:
      name: startDate
      in: query
      description: Start date for which to retrieve the history formatted as ISO
      required: true
      schema:
        type: string
        format: date
      example: 1997-8-25
    countryId:
      name: id
      in: path
      description: ISO 3166-1 ALPHA-3 Code of the country to retrieve
      required: true
      schema:
        type: string
      example: ESP
    resolution:
      name: resolution
      in: query
      description: Dimension for which to retrieve the history
      required: false
      schema:
        enum:
        - year
        - month
        - day
        default: month
  schemas:
    NamedPercentage:
      description: Named percentage
      type: object
      properties:
        name:
          type: string
          example: true
        percentage:
          type: number
          format: double
          example: 50.5
    HistoricReusability:
      description: Reusability metrics
      type: object
      properties:
        licenceAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        licenceAlignment:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        accessRightsAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        accessRightsAlignment:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        contactPointAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        publisherAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        score:
          $ref: '#/components/schemas/HistoricScore'
    HistoricFindability:
      description: Findability metrics
      type: object
      properties:
        keywordAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        categoryAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        spatialAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        temporalAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        score:
          $ref: '#/components/schemas/HistoricScore'
    Contextuality:
      description: Contextuality metrics
      type: object
      properties:
        rightsAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        byteSizeAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        dateIssuedAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        dateModifiedAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        score:
          description: The aggregated score
          type: object
          items:
            $ref: '#/components/schemas/PointPercentageMax'
          example:
            point: 55.0
            percentage: 55.0
            max: 80.0
    Accessibility:
      description: Accessibility metrics
      type: object
      properties:
        accessUrlStatusCodes:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: 200
            percentage: 92.0
          - name: 400
            percentage: 1.0
          - name: 404
            percentage: 1.0
          - name: 1300
            percentage: 2.0
          - name: 405
            percentage: 3.0
          - name: 1100
            percentage: 1.0
        downloadUrlAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        downloadUrlStatusCodes:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
        score:
          description: The aggregated score
          type: object
          items:
            $ref: '#/components/schemas/PointPercentageMax'
          example:
            point: 55.0
            percentage: 55.0
            max: 80.0
    HistoricContextuality:
      description: Contextuality metrics
      type: object
      properties:
        rightsAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        byteSizeAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        dateIssuedAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        dateModifiedAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        score:
          $ref: '#/components/schemas/HistoricScore'
    PointPercentageMax:
      description: Point Percentage Max
      type: object
      properties:
        point:
          type: number
          format: double
          example: 50.5
        percentage:
          type: number
          format: double
          example: 50.5
        max:
          type: number
          format: double
          example: 80.0
    CountryMetrics:
      type: object
      properties:
        info:
          type: string
        findability:
          $ref: '#/components/schemas/Findability'
        accessibility:
          $ref: '#/components/schemas/Accessibility'
        interoperability:
          $ref: '#/components/schemas/Interoperability'
        resusability:
          $ref: '#/components/schemas/Reusability'
        contextuality:
          $ref: '#/components/schemas/Contextuality'
        score:
          description: The aggregated score
          type: number
          format: int32
    Reusability:
      description: Reusability metrics
      type: object
      properties:
        licenceAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        licenceAlignment:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        accessRightsAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        accessRightsAlignment:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        contactPointAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        publisherAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        score:
          description: The aggregated score
          type: object
          items:
            $ref: '#/components/schemas/PointPercentageMax'
          example:
            point: 55.0
            percentage: 55.0
            max: 80.0
    HistoricScore:
      description: List of name value pairs, where key is the date and value is the score.
      type: object
      properties:
        score:
          type: array
          items:
            type: object
            additionalProperties:
              type: integer
      example:
      - '2020-03-02': 200.0
      - '2020-03-03': 221.0
      - '2020-03-04': 221.0
    HistoricNamedPercentages:
      description: A history of named percentages.
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NamedPercentage'
      minProperties: 1
    Interoperability:
      description: Interoperability metrics
      type: object
      properties:
        formatAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        mediaTypeAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        formatMediaTypeAlignment:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        formatMediaTypeNonProprietary:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        formatMediaTypeMachineReadable:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        dcatApCompliance:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        score:
          description: The aggregated score
          type: object
          items:
            $ref: '#/components/schemas/PointPercentageMax'
          example:
            point: 55.0
            percentage: 55.0
            max: 80.0
    HistoricCountryMetrics:
      type: object
      properties:
        info:
          type: string
          example: DEU
        findability:
          $ref: '#/components/schemas/HistoricFindability'
        accessibility:
          $ref: '#/components/schemas/HistoricAccessibility'
        interoperability:
          $ref: '#/components/schemas/HistoricInteroperability'
        resusability:
          $ref: '#/components/schemas/HistoricReusability'
        contextuality:
          $ref: '#/components/schemas/HistoricContextuality'
        score:
          $ref: '#/components/schemas/HistoricScore'
    HistoricInteroperability:
      description: Interoperability metrics
      type: object
      properties:
        formatAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        mediaTypeAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        formatMediaTypeAlignment:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        formatMediaTypeNonProprietary:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        formatMediaTypeMachineReadable:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        dcatApCompliance:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        score:
          $ref: '#/components/schemas/HistoricScore'
    HistoricAccessibility:
      description: Accessibility metrics
      type: object
      properties:
        accessUrlStatusCodes:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: 200
              percentage: 55.0
            - name: 404
              percentage: 45.0
          - '2020-03-03':
            - name: 200
              percentage: 33.0
            - name: 404
              percentage: 67.0
          - '2020-03-04':
            - name: 200
              percentage: 82.5
            - name: 500
              percentage: 17.5
        downloadUrlAvailability:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: true
              percentage: 55.0
            - name: false
              percentage: 45.0
          - '2020-03-03':
            - name: true
              percentage: 33.0
            - name: false
              percentage: 67.0
          - '2020-03-04':
            - name: true
              percentage: 82.5
            - name: false
              percentage: 17.5
        downloadUrlStatusCodes:
          type: array
          items:
            $ref: '#/components/schemas/HistoricNamedPercentages'
          example:
          - '2020-03-02':
            - name: 200
              percentage: 55.0
            - name: 404
              percentage: 45.0
          - '2020-03-03':
            - name: 404
              percentage: 33.0
            - name: 500
              percentage: 67.0
          - '2020-03-04':
            - name: 200
              percentage: 82.5
            - name: 500
              percentage: 17.5
        score:
          $ref: '#/components/schemas/HistoricScore'
    Findability:
      description: Findability metrics
      type: object
      properties:
        keywordAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        categoryAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        spatialAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        temporalAvailability:
          type: array
          items:
            $ref: '#/components/schemas/NamedPercentage'
          example:
          - name: true
            percentage: 55.0
          - name: false
            percentage: 45.0
        score:
          description: The aggregated score
          type: object
          items:
            $ref: '#/components/schemas/PointPercentageMax'
          example:
            point: 55.0
            percentage: 55.0
            max: 80.0
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
